<!DOCTYPE html>
<html>
<head>
  <title>
Istoria aviației române
</title>
<link rel="icon" href="poze/stema.png" type="image" size="12x16">


<style>
.btn-group {
	padding: 2% 4% 3% 4%;

}

.btn-group .button {
  background-color: #0000CD; 
  border: none;
  color: white;
  padding: 18px 33px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  cursor: pointer;
  float: left;
  width: 7%;
}

.btn-group .button:hover {
  background-color: 	#0000FF;
}
</style>
</head>
<body background="poze/fundal.png">

<center>
<img src="poze/imagine avion.jpg" alt="avion" width="22%">
</center>

<div class="btn-group">
  <a href="index1.php" class="button">Acasă</a>
  <a href="personalitati.php" class="button">Personalități</a>
  <a href="galerie.php" class="button">Galerie foto</a>
  <a href="ulm.php" class="button">ULM</a>
  <a href="avioane.php" class="button">Avioane</a>
  <a href="hidroavioane.php" class="button">Hidroavioane</a>
  <a href="planoare.php" class="button">Planoare</a>
  <a href="constructori.php" class="button">Începuturi</a>

</div><br>
	<font  size=5 >
<div style="text-align: justify; text-indent: 40pt; margin: 5% 8% 0% 8%"> Ca urmare a participării României la Primul Război Mondial, Atelierele școlii militare de pilotaj de la Cotroceni au fost mutate la Iași, unde - sub denumirea <b>Rezerva generală a aviației</b> (R.G.A.) - au făcut față nevoilor de front ale aviației noastre.</div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%">	În anii 1917-1918, la R.G.A. au fost recondiționate și montate toate avioanele primite din Franța și, în plus, fapt cu totul remarcabil, ținând seama de condițiile de lucru și de utilajul ce-l avea la dispoziție, a fost reparat un număr de 292 de avioane degradate sau avariate în luptă. Tot la R.G.A. au fost reparate și redate în funcțiune 545 motoare de avion. </div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%"> 	În anul 1919, după încetarea ostilităților, a luat ființă la București (pe câmpul de la Cotroceni) Arsenalul aeronautic, prin transferarea întregului utilaj și personal tehnic de la Rezerva generală a aviației din Iași.</div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%">La <b>Arsenalul aeronautic</b>, în anul 1922, a început construirea în serie a avionului biloc german de observație și recunoaștere Brandenburg, echipat cu un motor Austro-Daimler de 160 C.P. Până la sfârșitul anului au fost terminate și date în serviciu 72 avioane de acest tip. De asemenea, șase avioane militare de bombardament, de tip De Havilland, prin modificarea fuzelajului, au fost transformate și adaptate pentru transportul de pasageri, în scopul folosirii lor pe liniile aeriene care au luat ființă în țara noastră în anul 1925. În anii următori au mai fost construite aici două prototipuri de avioane românești: Proto-1 și Aeron. </div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%">	Având un potențial de fabricație redus, cu ateliere neîncăpătoare și mașini-unelte insuficiente și demodate, Arsenalul aeronautic nu mai putea face față cerințelor crescând ale aviației aflată în plină dezvoltare. Ca urmare a acestei situații s-a făcut tot mai mult simțită necesitatea (pe care Vlaicu o întrevăzuse) de a se crea o industrie aeronautică națională. O asemenea realizare era condiționată, printre altele, de existența unui personal tehnic aeronautic, suficient ca număr și cu o pregătire corespunzătoare. </div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%"> 	Primii ingineri români de aeronautică și-au făcut studiile în Franța, unde au absolvit Școala superioară de aeronautică și construcție mecanică, cea dintâi școală aeronautică de specialitate din lume. Printre aceștia au fost: Henri Condă (promoția 1910), Stanislas Șeșefski și Constantin Gheorghiu (1913), ultimul devenit după absolvire director tehnic al Școlii și atelierelor de la Chilia, precum și sublocotenenții Ștefan Protopopescu și Gheorghe Negrescu (promoția 1911). Ulterior, alți ingineri români au absolvit școli aeronautice de specializare în Italia, Germania și Anglia.</div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%"> 	Începând cu anul 1928, în România au fost puse bazele învățământului tehnic aeronautic superior, prin înființarea unei catedre de specialitate în cadrul Facultății de mecanică de pe lângă Școala Politehnică din București, catedră care în anul 1934 a deveit secție.</div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%">Nu aceeași era situația în ceea ce privește personalul tehnic mediu și inferior al aviației noastre, insuficient numeric și deficitar ca pregătire din cauza lipsei unor școli de specializare corespunzătoare. În anul 1921 a luat ființă, în cadrul aeronauticii militare (pe aerodromul Pipera), prima școală de meseriași pentru aviație. În anul 1924, această școală a fost mutată la Mediaș, în clădiri dispunând de instalații corespunzătoare, și transformată în Școala tehnică a aeronauticii, cu o durată de învățământ de 6, 7 și 8 ani. O parte din absolvenții acestei școli își continuau studiile, devenind ofițeri mecanici, iar unii dintre ei ingineri de aeronautică. Tot în anul 1924 au luat ființă școlile pregătitoare și speciale ale aeronauticii, printre care o școală pregătitoare de ofițeri mecanici, cu o durată de învățământ de doi ani, și o școală pregătitoare de ofițeri de rezervă, ingineri de aeronautică.</div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%"> 	Cu asemenea cadre bine pregătite de ingineri și tehnicieni, formați atât în școlile noastre, cât și în cele din străinătate, a fost posibilă crearea unui serviciu tehnic al aeronauticii. Acest serviciu luase ființă, de fapt, cu posibilități modeste, încă de la data de 15 septembrie 1915, o dată cu Corpul de aviație, când aviație și aerostația, subordonate până atunci armei geniului, au devenit o armă de sine stătătoare.</div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%"> Serviciul tehnic al aeronauticii, la a cărui conducere au fost mult timp locotenentul-colonet inginer aviator Gherghe Negrescu și maiorul inginer aviator Constantin Mincu, a avut, ca organ de îndrumare și control, un rol determinant și pentru dezvoltarea industriei noastre aeronautice.</div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%"> 	Prima fabrică românească care, după Primul Război Mondial, a început să construiască avioane a fost <b> Astra</b> din Arad, unde până în anul 1923 se fabricaseră exclusiv vagoane de cale ferată. În acest an, la Astra s-a construit un prototip de avion, conceput și proiectat de inginerul Stanislas Șeșefski. S-a continuat apoi producția aeronautică cu o serie de avioane Proto-2, derivate din avionul Proto-1, al cărui prototip, conceput de maiorul inginer aviator Ștefan Protopopescu, fusese construit cu un an înainte la Arsenalul aeronautic din București. Din colectivul de tehnicieni care la fabrica Astra s-a ocupat de construcția de avioane au făcut parte, printre alții, inginerii de aeronautică Radu Onciul, Victor Feodorov și Dumitru Barbieri. În anul 1925 la Astra s-a mai realizat un prototip de avion de recunoaștere, denumit Astra-Proto, după proiectul maiorului inginer aviator Ștefan Protopopescu, dar care nu a fost construit în serie. În același an producția de avioane a acestei fabrici a încetat, deoarece utilajul și personalul de specialitate au fost transferate la noile uzine I.A.R. din Brașov, rămânând ca la Arad să se fabrice, în continuare, vagoane de cale ferată. Menționăm că la Astra s-au fabricat și motoare Martha-Benz de 250 C.P. pentru avioane.</div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%">	În anul 1920 a luat ființă o escadrilă de hidroavioane. În anii 1923 și 1924 ea și-a încetat activitatea de zbor din cauza învechirii materialului volant. În această situație, Sociatatea de transport Constanța (S.T.C.) a luat inițiativa de a construi o serie de hidroavioane. Nu s-a reușit însă decât construirea unei singure serii de patru hidroavioane, denumite S.T.C.-R.A.S.-1, după proiectul inginerului Radu Stoika. În anul 1927, S.T.C. și-a încetat activitatea legată de producția aeronautică, nefiind sprijinită pentru construirea și extinderea construcției de hidroavioane românești și în licență, așa cum își propusese. </div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%">	Realizarea primelor avioane românești în perioada 1922-1925 a constituit un început promițător pentru dezvoltarea unei industrii aeronautice națioanele </div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%"> 	În anul 1925 s-au pus bazele unei industrii aeronautice românești moderne, care s-a dezvoltat în anii următori, astfel încât în preajma izbucnirii celui de Al Doilea Război Mondial ea cuprindea: uzinele I.A.R. din Brașov, fabricile S.E.T. și I.C.A.R., întreprinderea A.S.A.M. (cu sucursale în mai multe orașe) și un număr de unități auxiliare (realizările Ministerului aerului și marinei de la înființare și până în 1939), de a căror realizări ne vom ocupa în continuare.</div>
<div style="text-align: justify; text-indent: 40pt; margin: 2% 8% 0% 8%">	<b>Uzinele I.A.R. (Industria Aeronautică Română)</b> din Brașov au fost înființate în anul 1925, sub forma unei societăți pe acțiuni, capitalul lor inițial fiind acoperit de un grup francez (reprezentant al uzinelor Bleriot-Spad și Lorraine-Dietrich), de fabrica Astra din Arad, care a adus ca aport utilajul ei de specialitate, și de statul român, a cărui participare consta în numerar și în valoarea terenului afectat pentru construcția uzinelor și pentru amenajarea unui aerodrom propriu.</div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%"> 	Treptat, statul român a cumpărat acțiunile deținute de firmele franceze, astfel că la 1 ianuarie 1939 uzinele I.A.R., reorganizate sub formă de regie autonomă de stat, au devenit în întregime românești</div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%"> La uzinele I.A.R. din Brașov au fost construite multe tipuri de avioane, de concepție proprie sau în licență, de toate categoriile: de școală și de antrenament, de sport și turism aerian,   de mare raid, precum și avioane militare de vânătoare, de asalt, de bombardament în picaj, de observație, de recunoaștere, de bombardament.</div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%"> 	Prima comandă pentru nevoile aviației militare au constituit-o 30 de avioane Morane-Saulnier M.S.-35 (biloc de școală), serie care a fost terminată în toamna anului 1928. Aceste avioane, ca și cele din comanda următoare, 70 de avioane de recunoaștere și bombardament Potez-XXV, s-au executat pe baza licențelor de fabricație obținute de la uzinele franceze respective.</div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%"> 	Primul avion, purtând denumirea I.A.R., a  ieșit pe porțile uzinelor în anul 1930. Era prototipul unui avion de vânătoare I.A.R.-C.V. 11, realizat după proiectul inginerului Elie Carafoli în colaborare cu inginerul francez Virmoux. Formula adoptată (monoplan cu aripa jos), precum și calitățile sale de zbor îl plasau printre cele mai bune avioane din lume în categoria respectivă. Dintre cele peste 20 de tipuri de avioane construite la uzinele I.A.R. din Brașov, în decursul celor aproape 18 ani de activitate, s-au remarcat în mod deosebit, prin performanțele lor, următoarele: I.A.R.-16, cu care în anul 1935 a fost stabilit un valoros record național de înălțime (11.631 m), I.A.R.-39, folosit mulți ani în aviația noastră de cercetare, precum și avionul de vânătoare I.A.R.-80, cu varianta de bombardament în picaj I.A.R.-81. La uzinele I.A.R. din Brașov a fost realizat și avionul de cercetare îndepărtată I.A.R.-47, monoplan cu aripa jos, având un echipaj de trei persoane. Din cele trei exemplare construite, unul a fost destinat pentru probele statice de rezistență a celulei, cu al doilea s-au efectuat zborurile de încercare pentru stabilirea performanțelor, iar al treilea exemplar nu a fost terminat. </div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%"> 	Trebuie să subliniem că în perioada 1927-1944 producția de avioane a uzinelor I.A.R. din Brașov a fost una din cele mai prestigioase și reprezentative pentru construcția aeronautică din țara noastră.</div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%">	În afară de avioane și motoare, la uzinele IA.R. din Brașov au fost fabricate, de asemenea, unele instalații și accesorii pentru armamentul de bord, ca de exemplu:  </div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%">	- lansatorul de bombe Barbieri (după numele constructorului, inginer în cadrul uzinei), realizat în anul 1931 pentru avioanele Potez-XXV; lansatorul era superior celor procurate din străinătate; </div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%">	- turele de mitralieră Grosu (purtând numele proiectantului, inginer la I.A.R.), pentru avioanele Potez-XXV și Potez-54. </div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%">	Au mai fost proiectate și construite turele de mitralieră pentru avioanul I.A.R.-37 și arcade de mitralieră pentru avionul I.A.R.-38 și I.A.R.-39. </div>
<div style="text-align: justify; text-indent: 40pt; margin: 2% 8% 0% 8%"> <b>	S.E.T. (Societatea pentru exploatări tehnice) </b> poate fi considerată, ca valoare și volum al producției sale, a doua unitate industrială aeronautică după uzinele I.A.R. Ea a luat ființă în anul 1923, când inginerul Grigore Zamfirescu, diplomat al Școlii superiaore de aeronautică din Paris, a obținut concesiunea atelierelor mecanice ale unei cooperative din București, transformându-le într-o întreprindere în cadrul căreia, în anul 1924, a fost creată o secție de construcții aeronautice, care și-a început activitatea cu:</div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%"> 	- transformarea a 4 avioane militare de tip <i>De Havilland </i>în avioane de pasageri (pentru aviația civilă de transport);</div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%"> 	- reparații generale și revizii ale avioanelor Proto-2, construite la Astra din Arad și aflate în serviciul Școlii militare de pilotaj de la Tecuci;</div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%">- executarea proiectului și construcția unui avion de recunoaștere și bombardament de zi. </div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%"> 	Proiectul și realizarea acestui prim avion fabricat la S.E.T. a fost rezultatul colaborării dintre inginerii Șt. Protopopescu, Grigore Zamfirescu și Dumitru Baziliu (detașat în acest scop de la Direcția superioară a aeronauticii). Memoriul cu descrierea acestui avion, denumit Proto-S.E.T., a fost înregistrat la Oficiul de investiții de pe lângă Ministerul industriei și comerțului, la nr. 11.055 din 28 noiembrie 1924. Deși a dovedit calități bune de zbor, în comparație cu avioanele străine aflate la acea vreme în serviciul aeronauticii noastre, avionul Proto-S.E.T. nu a fost construit în serie.</div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%"> 	La fabrica S.E.T. au fost construite atât avioane de concepție proprie, cât și în licență. Din producția proprie s-au evidențiat, prin calitățile lor, avioanele: S.E.T.-3, S.E.T.-31, S.E.T.-7 KD, S.E.T.-41, S.E.T.-31 G. Prototipurile S.E.T.-X (avion de antrenament pentru aviația de vânătoare) și S.E.T.-XV (avion biplan de vânătoare) nu au fost construite în serie. Tot în fază de prototip au rămas și avioanele S.E.T.-41 R (avion de mare raid) și S.E.T.-4 S (avion de antrenament). Construcțiile realizate în licență au fost: 80 de avioane Fleet F-10 G și 124 de avioane Nardi F.N.-305, precum și un prototip modificat al avionului francez de vânătoare Spad. Ultimul proiect realizat în cadrul fabricii S.E.T. a fost cel al unui bimotor monoplan S.E.T.-20, care, însă, nu a depășit stadiul încercărilor în laborator. Datorită dezvoltării la care ajunsese fabrica S.E.T., statul i-a repartizat și executarea unui număr de 80 de avioane I.A.R.-27 și 96 de avioane I.A.R.-39. La S.E.T. a mai fost construită, în anul 1946 (în licență), o serie de 40 de planoare Grunau Baby II-B, cu modificări constructive efectuate de inginerul Alexandru Marcu.</div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%"> 	Pentru unele tipuri de avioane destinate aviației militare, la fabrica S.E.T. au fost proiectate și construite și diferite accesorii pentru armamentul de bord, ca de exemplu turela de mitralieră S.E.T. (montată pe avioanele S.E.T-7 K și S.E.T.-7 KD).</div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%">	În anul 1938, printr-o convenție încheiată cu Ministerul aerului și marinei, care îi asigurase comenzi pe o durată de 5 ani, la Târgu Ocna urma să fie creată pe bazele fabricii S.E.T. o întreprindere modernă de construcții aeronautice (avioane și motoare), cu denumirea S.E.T.-I.N.A. (S.E.T.-<i>Industria națională aeronautică</i>). Izbucnirea celui de Al Doilea Război Mondial a împiedicat  realizarea acestui proiect. </div>
<div style="text-align: justify; text-indent: 40pt; margin: 2% 8% 0% 8%"> 	<b>I.C.A.R. (Întreprinderea de construcții aeronautice românești) </b>a luat ființă în anul 1932, din inițiativa și sub conducerea inginerului Mihail Racoviță. Producția acestei întreprinderi a fost orientată aproape exclusiv spre construirea de avioane ușoare, ulterior și planoare, destinate aviației civile. Dintre avioanele construite se detașează avionul I.C.A.R.-Universal (monoloc) de acrobație. I.C.A.R.-Universal (biloc) de școală, antrenament și turism, cu care a fost executat în anul 1935 un reușit raid în formație pe traiectul București-Capetown-București, și I.C.A.R.-Comercial, avion de transport, care a fost folosit în perioada 1936-1938 pe liniile interne de pasageri.</div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%"> 	În secția de planoare, condusă de inginerul Nicolae Racoviță, au fost construite în serie planoare de școală faza I I.C.A.R.-1, precum și planoare Grunau Baby II B.</div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%"> 	La dezvoltarea întreprinderii au contribuit, printre alții, inginerii D. Bulgaru și V. Timoșenco.</div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%">	În anul 1938, Ministerul aerului și marinei a încheiat și cu fabrica I.C.A.R. o convenție prin care acesteia i se asigura un volum sporit de comenzi în vederea dezvoltării producției. Sub denumirea de <i>Uzinele I.C.A.R.-Societate Anonimă</i>, ea urma să fie mutată în Transilvania, în clădiri noi, cu instalații moderne. Ca și în cazul întreprinderii S.E.T.-I.N.A., nici proiectul referitor la dezvoltarea fabricii I.C.A.R. nu s-a realizat, din aceeași cauză. </div>
<div style="text-align: justify; text-indent: 40pt; margin: 2% 8% 0% 8%"> Dintre întreprinderile auxiliare care au înlesnit producția întreprinderilor aeronautice principale arătate mai sus, menționăm fabricile S.E.M.A.T. și <i>Forja Poldi-I.A.R.</i></div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%"> <b>	S.E.M.A.T. (Societatea pentru exploatarea de materiale aeronautice și tehnice) </b>a fost înființată în anul 1934, sub conducerea locotenentului aviator în rezervă Ion Simionescu. În atelierele întreprinderii S.E.M.A.T. au fost fabricate, în serie, piese componente pentru trenuri de aterizare escamotabile de diferite tipuri, după licențele conoscutei fabrici franceze de specialitate Messier. Aceste piese erau destinate uzinelor I.A.R., pentru avioanele I.A.R.-80 și J.R.S.-Savoia Marchetti-79 B. Au mai fost fabricate unele accesorii, ca, de exemplu, dispozitive de sincronizare pentru tragerea cu armamentul de bord prin câmpul de rotație al elicei.</div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%"> <b>	Forja Poldi-I.A.R.</b> a fost construită la Brașov în anul 1937, cu aportul financiar și tehnic al oțelăriilor cehoslovace Poldi-Hutte. Această forjă livra piese brute forjate (care până atunci se procurau exclusiv din străinătate), acoperind în mare parte nevoile de oțel ale industriei noastre aeronautice.</div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%">Trebuie să adăugăm că și alte întreprinderi, nespecializate, au furnizat industriei aeronautice unele piese sau materiale. Astfel de întreprinderi au fost: <i>Industria silvică din Maramureș</i>, principala furnizoare de placaj, <i>Societatea Jaquard</i> din Sighișoara, care a livrat pânză de avion și pânză de mătase pentru parașute, I.F.M.F. (Industria de fabricație metale feroase) din București, care a produs (în special pentru fabrica I.C.A.R.) rezervoare de aluminiu sudate, capotaje și carenaje, colectoare de eșapament din oțel inoxidabil etc. </div>
<div style="text-align: justify; text-indent: 40pt; margin: 2% 8% 0% 8%"> 	În perioada de început a industriei aeronautice din România se utilizau materii prime și semifabricate indigene în proporție de numai 12% pentru avioanele de construcție mixtă (lemn și metal) și de 6% pentru cele metalice. Se procurau din străinătate (în special din Franța) aluminiu, duraluminiu, oțeluri speciale, contraplacaje, ulei de ricin, pânză de avioane, lacuri și vopsele, piese turnate, piese forjate etc. Treptat, aceste materiale, cu excepția aluminiului, a bronzului și a oțelurilor speciale, au început să fie livrate de întreprinderile din țara noastră, ajungându-se ca în 1939, procentul de materiale indigene folosite în industria noastră aeronautică să crească până la 50%.</div>
<div style="text-align: justify; text-indent: 40pt; margin: 2% 8% 0% 8%"> 	Anul 1939 a marcat un efort maxim pentru dezvoltarea industriei noastre aeronautice. Arsenalul aeronautic din București (unde se construiseră primele avioane în serie), după o perioadă de stagnare a căpătat, cu începerea de la 1 iunie 1939, o nouă dezvoltare și destinație, ca urmare a înființării unei importante întreprinderi, denumită A.S.A.M.</div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%"> <b>A.S.A.M. (Administrația stabilimentelor Aeronauticii și Marinei)</b> a grupat în compunerea sa: Arsenalul aeronautic, ca unitate centrală, precum și atelierele de revizie și reparație ale unităților militare de aviație de la Pipera (București), Mediaș, Galați, Tecuci și Iași, iar pentru marină - Arsenalul Marinei de la Galați.</div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%">	Scopul creării acestei noi întreprinderi autonome de stat, care ca pondere industrială devenise a doua după I.A.R., era de a asigura reparațiile de material volant și de a confecționa piese de schimb pentru avioanele și motoarele în serviciu. </div>
<div style="text-align: justify; text-indent: 40pt; margin: 2% 8% 0% 8%">	În afara construcțiilor originale, deosebit de valoroase, amintim că în acest interval de timp a mai fost construită, în licență, o serie de avioane, dintre care unele consacrate pe plan mondial ca tipuri reprezentative pentru firme de prestigiu din țări cu vechi tradiții în domeniul aviației, cum sunt: Franța, Germania, Italia, Polonia etc. </div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%">	Acest fapt dovedește buna organizare și dotare a industriei aeronautice românești, nivelul corespunzător de pregătire al personalului, precum și calitatea materialelor folosite, care în majoritate erau produse în țară. Trebuie, de asemenea, menționat că unora dintre avioanele contruite în licență li s-au adus îmbunătățiri substanțiale față de construcția originară, care au constat uneori, chiar în modificarea celulei sau în înlocuirea motoarelor originale cu motoare de fabricație românească. </div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%">Primele avioane străine construite în țara noastră au fost, așa cum s-a amintit, Farman, mai întâi la atelierele Școlii de pilotaj de la Chitila și apoi la ale celei de la Cotroceni, Brandenburg, la Arsenalul aeronautic, Morane-Saulnier M.S.-35 și Potez-XXI, cu care și-a început activitatea uzina I.A.R. din Brașov. </div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%"> Și dacă unele din avioanele fabricate în licență, ca, de exemplu, Fleet F-10 G, P.Z.L.-11, P.Z.L.-24 sau Messerschmitt Me-109, constituiau o reproducere a construcțiilor originale respective, cu deosebirea că la primele trei tipuri motoarele au fost înlocuite cu motoare construite în țara noastră, bimotorul Savoia Marchetti S-79 B a fost construit într-o variantă nouă, realizată pe baza studiilor și calculelor efectuate de colectivul uzinelor I.A.R. La această variantă nouă a fost modificată celula (inclusiv ampenajul), rezultând un avion deosebit față de versiunea originală, căruia i s-a dat denumirea de J.R.S.-79 B. La Fleet F-10 G, deși nu s-a înlocuit decât motorul, modificarea era vizibilă în profilul avionului, deoarece motorul original, tip Kinner de 115 C.P., în stea, a fost înlouit cu un motor în linie, I.A.R. Gipsy Major-4.</div>
<div style="text-align: justify; text-indent: 40pt; margin: 2% 8% 0% 8%">	În afară de avioanele menționate mai sus, fabricate în serie la I.A.R.(Brașov), au mai fost construite în licență la S.E.T.: avionul de vânătoare Spad, căruia i s-a modificat celula, ameliorându-i-se prin aceasta performanțele de zbor, avionul de școală și antrenament Nardi F.N.-305, precum și un număr de 80 de avioane Fleet F-10 G. </div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%">La fabrica I.C.A.R. a fost construit conoscutul avion de legătură, observație și comandament Fieseler F-10 G. </div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%"> 	În legătură cu avioanele de fabricație străină, construite sau transformate în țara noastră, amintim că la <i>Centrul tehnico-industrial aeronautic Pipera</i>, în anul 1956 s-a executat transformarea avionului monoloc de vânătoare, cu reacție, Iak-23, într-o variantă cu dublă comandă pentru instruirea piloților militari.</div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%"> După terminarea celui de Al Doilea Război Mondial, la fabrica I.A.R. din Brașov, transformată în uzina <i>Tractorul</i>, s-a menținut un atelier de prototipuri (avioane și planoare) și experiențe, condus de inginerul Radu Manicatide, în cadrul căruia s-a reluat seria construcțiilor aeronautice, prin realizarea, în anul 1949 a avionului I.A.R.-811.</div>
<div style="text-align: justify; text-indent: 40pt; margin: 2% 8% 0% 8%">	În anul 1951 funcționau următoarele unități de construcții aeronautice: A.R.M.V.-1 (Atelierele de reparații material volant) la Mediaș, A.R.M.V.-2, pe aerodromul Pipera (București), U.R.M.V.-3 (Uzinele de reparații material volant), la Brașov. Ulterior la U.R.M.V.-3  a luat ființă și un atelier de reparații pentru celule sub conducerea inginerului Iosif Șilimon, unde s-a început și construirea planoarelor din seria denumită I.S </div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 0% 8%">	O altă unitate industrială de construcții aeronautice a fost I.F.I.L. (Întreprinderea forestieră pentru industrializarea lemnului) din Reghin, denumită mai târziu <i> Combinatul pentru industrializarea lemnului </i>(C.I.L.), unde a fost creată în anul 1950, sub conducerea lui Vladimir Novițchi, o secție pentru construcția de planoare și celule de avioane. </div>
<div style="text-align: justify; text-indent: 40pt; margin: 0% 8% 4% 8%">	Întreprinderea A.R.M.V.-2, denumită temporar C.T.I.A. (Centrul tehnic industrial aeronautic), iar din anul 1959, I.C.R.M.A. (Întreprinderea de construcții și reparații material aeronautic). În anul 1960, secția care funcționase sub conducerea inginerului Iosif Șilimon la U.R.M.V.-3 (pentru construcția de planoare) a fost preluată de <i>Întreprinderea de indusrie locală </i> din Ghimbav, unde au fost continuate proiectarea și construirea de planoare. Ulterior, la <b>I.C.A.(Întreprinderea de construcții aeronautice)</b> Brașov au fost realizate planoare românești complet metalice.  </div>
<div style="text-align: right; margin: 0% 8% 10% 0%"> <b>Construcții aeronautice românești 1905-1970</b> </div>

		
</body>
</html>
